name: Report
main: ImNotYourDev\Report\Report
api:
  - 3.9.0
  - 3.9.1
  - 3.9.2
  - 3.9.3
version: 1.0
author: ImNotYourDev

permissions:
  reportsystem.admin:
    description: open admin ui and report list
    default: op