name: Report
main: ImNotYourDev\Report\Report
api: 3.7.0
version: 1.3
author: ImNotYourDev

softdepend:
  - PixelgamesToDiscord

permissions:
  reportsystem.admin:
    description: open admin ui and report list
    default: op